runtime: python39 

env_variables: 
  OPENAI_KEY: "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"
  OPENAI_API_KEY: "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"
  SENDER_EMAIL: "ernie@promptlys.org"
  SENDER_PASSWORD: "kopkgtsewizildfc"

  LINE_ACCESS_TOKEN: "5cfQWSj3d7TolYC1LBMJMe1o7iA/Sd93zDQkCGfgUJU3cP07A084LyB4guym+CH4OcwfBOkzUItECfwJuxWcAL+m9oDX1ex5Co4Mz5CNQCN3PMM2N2pP3FeFZQUvYXn+iu+akoZgb6lpc/PEYdPIBQdB04t89/1O/w1cDnyilFU="
  LINE_CHANNEL_SECRET: "ca79f24ee0480468f82b319876b25a94"
  SUPABASE_URL: "https://msfpfmwdawonueqaevru.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZnBmbXdkYXdvbnVlcWFldnJ1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3NTk5MTE5MSwiZXhwIjoxOTkxNTY3MTkxfQ.ImwsqoISh3zCKcAW0FJeB13UCWOCVay5Fm1U5TNwhUU"

  GPT_KEY: "YES"
  APP_VERSION: "1.1"







